In [1]:
import torch
import torch.nn as nn

In [14]:
torch.manual_seed(43)
inputs = torch.tensor([1.0, 2.0,3.0,4.0])  # 1D

In [15]:
# activation function
neo = nn.Linear(in_features=4, out_features=1)

In [16]:
output = neo(inputs) 

In [17]:
output

tensor([-0.3571], grad_fn=<ViewBackward0>)

In [18]:
# verification

In [19]:
neo.weight

Parameter containing:
tensor([[-0.0460, -0.3035,  0.4210, -0.1538]], requires_grad=True)

In [20]:
neo.bias

Parameter containing:
tensor([-0.3519], requires_grad=True)

In [21]:
neo.weight @ inputs + neo.bias

tensor([-0.3571], grad_fn=<AddBackward0>)